{% set version = "0.9.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-kernelshap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/kernelshap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/kernelshap/kernelshap_{{ version }}.tar.gz
  sha256: 40bf27daf89d10771e2541853baa56377455141b5187186cf239878f268b359c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dofuture
    - r-foreach
  run:
    - r-base
    - r-dofuture
    - r-foreach

test:
  commands:
    - $R -e "library('kernelshap')"           # [not win]
    - "\"%R%\" -e \"library('kernelshap')\""  # [win]

about:
  home: https://github.com/ModelOriented/kernelshap
  license: GPL-2.0-or-later
  summary: Efficient implementation of Kernel SHAP (Lundberg and Lee, 2017, <doi:10.48550/arXiv.1705.07874>) permutation SHAP, and additive SHAP for model interpretability.  For Kernel SHAP and permutation SHAP, if the number of features is too large for exact calculations, the algorithms iterate until the SHAP values are
    sufficiently precise in terms of their standard errors.  The package integrates smoothly with meta-learning packages such as 'tidymodels', 'caret' or 'mlr3'. It supports multi-output models, case weights, and parallel computations.  Visualizations can be done using the R package 'shapviz'.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
